package com.pepero.jcb.api.enums;

public enum GameOverReason {
    CHECKMATE, STALEMATE, FIVEFOLD, SEVENTYFIVE_MOVES, INSUFFICIENTMATERIAL,
    FIFTYMOVES_CLAIM, THREEFOLD_CLAIM,
    AGREEMENTDRAW, RESIGNATION, TIMEOVER,
    THREE_CHECK, KING_OF_THE_HILL, HORDE, GIVEAWAY, SUICIDE, ATOMIC, KING_RACE,
    ADJUDICATION,
    NOTGAMEOVER
}
