package com.pepero.jcb.api.enums;

public enum GameOverReason {
    CHECKMATE, STALEMATE, FIVEFOLD, SEVENTYFIVE_MOVES, INSUFFICIENTMATERIAL,
    FIFTYMOVES_CLAIM, THREEFOLD_CLAIM,
    AGREEMENTDRAW, RESIGNATION, TIMEOVER,
    ADJUDICATION,
    NOTGAMEOVER
}
