package com.pepero.jcb.api.enums;

public enum GameOverReason {
    CHECKMATE, STALEMATE, THREEFOLD, FIFTYMOVES, INSUFFICIENTMATERIAL,
    AGREEMENTDRAW, RESIGNATION, TIMEOVER,
    ADJUDICATION,
    NOTGAMEOVER
}
